const DB = {
  page: 1,
  total_pages: 1,
  results: [
    {
      id: 571891,
      video: false,
      vote_count: 43,
      vote_average: 7,
      title: "Pokémon: Mewtwo Strikes Back - Evolution",
      release_date: "2019-07-12",
      original_language: "ja",
      original_title: "劇場版ポケットモンスター ミュウツーの逆襲 EVOLUTION",
      genre_ids: [28, 12, 16, 14, 10751],
      backdrop_path: "/olQLBp49qFpbWSt0z5OdNpFHP3g.jpg",
      adult: false,
      overview:
        "After a scientific experiment leads to the creation of Mewtwo, he sets out to destroy the world. Satoshi and his friends then decide to thwart Mewtwo's evil plans.",
      poster_path: "/ou7m7tnfb2bcE8LcFgUJzAwN2R8.jpg",
      popularity: 22.074,
      media_type: "movie"
    },
    {
      popularity: 0,
      id: 679929,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Cendrillon, le spectacle musical",
      release_date: "",
      original_language: "en",
      original_title: "Cendrillon, le spectacle musical",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        "is a musical comedy directly inspired by the eponymous tale, directed by Agnès Boury at the Mogador theater in Paris, from 2009 to 2013.",
      poster_path: null
    },
    {
      popularity: 0,
      vote_count: 0,
      video: false,
      poster_path: "/1rFb9Nv3na4FYsnlt90jhxv5OA8.jpg",
      id: 679904,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Junkie",
      genre_ids: [28, 80, 18],
      title: "Junkie",
      vote_average: 0,
      overview:
        "A rock bottom junkie trades a needle for a gun and sparks an explosive conflict with the local cartel, when you've lost the will to live, you ain't afraid to die. - inspired by true events (AKA: Miles to go).",
      release_date: "2019-02-08"
    },
    {
      popularity: 0,
      id: 679927,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Sword Dynasty: Fantasy Masterwork",
      release_date: "2020-02-18",
      original_language: "zh",
      original_title: "剑王朝之孤山剑藏",
      genre_ids: [28, 18, 9648, 10749],
      backdrop_path: "/cqWo2KkiuEHsbAl4O9d2XordCSI.jpg",
      adult: false,
      overview: "Coming Soon",
      poster_path: "/b43ETkznhjP5OTzhIKS72w1Gk5P.jpg"
    },
    {
      id: 330457,
      video: false,
      vote_count: 2591,
      vote_average: 7,
      title: "Frozen II",
      release_date: "2019-11-20",
      original_language: "en",
      original_title: "Frozen II",
      genre_ids: [12, 16, 10751],
      backdrop_path: "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
      adult: false,
      overview:
        "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
      poster_path: "/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
      popularity: 127.227,
      media_type: "movie"
    },
    {
      popularity: 0.6,
      id: 594916,
      video: false,
      vote_count: 1,
      vote_average: 10,
      title: "3 Bahadur: Rise of the Warriors",
      release_date: "2018-12-14",
      original_language: "ur",
      original_title: "3 Bahadur: Rise of the Warriors",
      genre_ids: [16, 28, 12, 14],
      backdrop_path: null,
      adult: false,
      overview:
        "The kids are going about their lives like other children, at times finding it difficult to control their powers. It is only during a school trip when they run into the mysterious circus performer, Erma , that things start to heat up.",
      poster_path: "/9F6vzPMrWfpX1xLyYolxyQT0jWu.jpg"
    },
    {
      popularity: 0,
      id: 680141,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "I can't holdback love",
      release_date: "2018-07-03",
      original_language: "xx",
      original_title: "Não posso adiar o amor",
      genre_ids: [35, 18],
      backdrop_path: null,
      adult: false,
      overview:
        "Based in António Ramos Rosa's landmark homonymous poem, I can't holdback love is a short tale for every age about life and love. Vicente has a love dilemma, having to choose between the passionate intensity of Francisco and the sweet tenderness of Joana. Featuring a violin performance.",
      poster_path: "/8WKAKNLw63UjFudRmVTlbSuNmqY.jpg"
    },
    {
      popularity: 0,
      vote_count: 0,
      video: false,
      poster_path: "/tv7CSXhEnbryZ4yP0U0cXS8KQUK.jpg",
      id: 680049,
      adult: false,
      backdrop_path: null,
      original_language: "zh",
      original_title: "萌妹特攻队",
      genre_ids: [18, 878],
      title: "萌妹特攻队",
      vote_average: 0,
      overview: "",
      release_date: "2019-03-09"
    },
    {
      popularity: 0,
      id: 680209,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Dinner",
      release_date: "",
      original_language: "de",
      original_title: "Mahlzeit",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: "A son triggers a dispute situation at a family dinner.",
      poster_path: null
    },
    {
      popularity: 1.607,
      vote_count: 11,
      video: false,
      poster_path: "/nVRqpAt2LYuUQdZsjltF0OUJC18.jpg",
      id: 45676,
      adult: false,
      backdrop_path: "/60hj7qPxPxMuGGO7lbrXTaAQsI.jpg",
      original_language: "ja",
      original_title: "Kiseichuu: Kiraa Pusshii",
      genre_ids: [35, 27],
      title: "Sexual Parasite",
      vote_average: 3.2,
      overview:
        "Five teenagers enter a deserted jungle and trespass inside an abandoned house only to haunted by a woman with a monster hidden inside her reproductive organs.",
      release_date: "2004-08-22"
    },
    {
      popularity: 1.342,
      vote_count: 14,
      video: false,
      poster_path: "/itz1361w7HtQDlGyBkAf4XmqmTW.jpg",
      id: 230714,
      adult: false,
      backdrop_path: "/bAYzk32m63U3vaZZO7UUAyrpn5A.jpg",
      original_language: "pt",
      original_title: "Quando Eu Era Vivo",
      genre_ids: [18, 27, 53],
      title: "When I Was Alive",
      vote_average: 5.6,
      overview:
        "After losing his job and the end of his marriage, Júnior returns to his father's house. But that is not his childhood house anymore. His old room has been rented by a young woman and the place feels unwelcome and oppressive. Júnior develops and obsession for his family history, as strange things start happening in the house.",
      release_date: "2014-01-31"
    },
    {
      popularity: 3.756,
      id: 328018,
      video: true,
      vote_count: 8,
      vote_average: 7.9,
      title: "Violetta en vivo",
      release_date: "2014-03-14",
      original_language: "en",
      original_title: "Violetta en vivo",
      genre_ids: [],
      backdrop_path: "/blUkK5aNTKonqA0kFRWxLifbstC.jpg",
      adult: false,
      overview:
        "Concert recorded live in Milan from 3 to 5 January 2014.\r They are just waiting for you!\r The students of Studio 21, Violetta, León, Diego and all other are on the scene of Mediolanum Forum in Milan to make you live an unforgettable concert.\r They interpret the must live songs from the first two seasons of your favorite series Disney Channel.\r Violetta The Concert DVD offers exceptional moments.\r Discover exclusive Violetta and her band at the heart of scenes to share with them their emotions before they climb on stage.\r Get ready to sing, dance and relive the greatest moments of the concert event.",
      poster_path: "/e8EpwLjkb2ZL1KgCBgAEQ1VRx0C.jpg"
    },
    {
      popularity: 22.094,
      vote_count: 0,
      video: false,
      poster_path: "/lFfwUaHqCaEnVntsmXcTuCyA2xc.jpg",
      id: 662192,
      adult: false,
      backdrop_path: "/oIbz3F9qvTuikS8T99fNNvG6z9s.jpg",
      original_language: "es",
      original_title: "Arjona Circo Soledad en Vivo",
      genre_ids: [],
      title: "Arjona Circo Soledad en Vivo",
      vote_average: 0,
      overview: "",
      release_date: "2019-08-30"
    },
    {
      popularity: 0.6,
      id: 503432,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Salut, pepperoni!",
      release_date: "2018-02-06",
      original_language: "fr",
      original_title: "Salut, pepperoni!",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview: "",
      poster_path: "/dSYuflBeJ3Kx2lMIZ5lsXA2E4Yw.jpg"
    }
  ]
};

export default DB;
